### ISSUE TITLE
关于rpc::rpc_error during call in function get_sensor_token

### ISSUE THREAD

**Issue by prograguo** [opendilab/LMDrive#26]
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 483, in main
    leaderboard_evaluator = LeaderboardEvaluator(arguments, statistics_manager)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 88, in __init__
    self.traffic_manager = self.client.get_trafficmanager(int(args.trafficManagerPort))
RuntimeError: rpc::rpc_error during call in function get_sensor_token
Exception ignored in: <function LeaderboardEvaluator.__del__ at 0x7fbd8e0e3f70>
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 127, in __del__
    self._cleanup()
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 139, in _cleanup
    if self.manager and self.manager.get_running_status() \
AttributeError: 'LeaderboardEvaluator' object has no attribute 'manager'
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 493, in <module>
    main()
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 489, in main
    del leaderboard_evaluator
UnboundLocalError: local variable 'leaderboard_evaluator' referenced before assignment

**Comment by BillChan226** [comment]
met the same issue. Does anyone have any idea?

**Comment by deepcs233** [comment]
Hi!
Sorry for the late reply, I have been very busy recently. It looks that the Carla simulator didn't start normally and the agent cannot connect the server. Maybe you can check the simulator's status and whether the port is being used.

**Comment by timbrist** [comment]
I assume that you are running the code with python3.8 and Client API version = 0.9.15. 
you need to use the carla-0.9.10-py3.7-win-amd64.egg instead of `pip install carla` (if you are using linux ) 

if you are using windows, the problem related to anaconda environments. see[ my comments](https://github.com/opendilab/LMDrive/issues/30#issuecomment-1987014416)
It seems like the team of Carla didn't support python3.8 to run carla-0.9.10-py3.7-win-amd64.egg, the only solution may be just run on Linux.

如果你要是用Windows这个问题有点无解， 我是装了Linux之后这个才解决这个问题。

**Comment by timbrist** [comment]
This problem is not related to LMDrive

try to run carla0.9.10.1 successfully before running the lmdrive script.
