### ISSUE TITLE
No such file or directory: 'sensor_pretrain.pth.tar.r50'

### ISSUE THREAD

**Issue by pastapeter** [opendilab/LMDrive#59]
I thought the pretrained weight would be on internet and download it by api. but error message says about no file sensor_pretrained.pth.tar.r50, is there any solution?

``
========= Preparing RouteScenario_3 (repetition 0) =========
> Setting up the agent
build model...

Could not set up the required agent:
> [Errno 2] No such file or directory: 'sensor_pretrain.pth.tar.r50'

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 270, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/home/dohyun/LMDrive/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "/home/dohyun/LMDrive/leaderboard/team_code/lmdriver_agent.py", line 205, in setup
    model = model_cls(preception_model=self.config.preception_model,
  File "/home/dohyun/LMDrive/LAVIS/lavis/models/drive_models/drive.py", line 86, in __init__
    pretrain_weights = torch.load(preception_model_ckpt, map_location=torch.device('cpu'))['state_dict']
  File "/home/dohyun/miniconda3/envs/lmdrive/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dohyun/miniconda3/envs/lmdrive/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dohyun/miniconda3/envs/lmdrive/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'sensor_pretrain.pth.tar.r50'
```

**Comment by shengyu889** [comment]
I had the same problem.Did you solve it?

**Comment by pastapeter** [comment]
Maybe you can download in https://huggingface.co/OpenDILabCommunity/LMDrive-vision-encoder-r50-v1.0/tree/main

**Comment by shengyu889** [comment]
Thank you so much!
