### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by CoderXuans** [opendilab/LMDrive#72]
@deepcs233
Hello,

After running ./leaderboard/scripts/run_evaluation.sh, I encountered the following issues:
/bin/bash: /home/mepus/anaconda3/lib/libtinfo.so.6: no version information available (required by /bin/bash)
bash: /home/mepus/anaconda3/lib/libtinfo.so.6: no version information available (required by bash)
chmod: 正在更改 '/home/syl/LMDrive/carla/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping' 的权限: 不允许的操作
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
leaderboard/leaderboard/leaderboard_evaluator.py
leaderboard/leaderboard/leaderboard_evaluator.py:24: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
import pkg_resources
/home/syl/LMDrive/leaderboard/leaderboard/utils/statistics_manager.py:223: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if route_record.status is not 'Completed':
localhost 16201
leaderboard/leaderboard/leaderboard_evaluator.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
if LooseVersion(dist.version) < LooseVersion('0.9.10'):
/home/mepus/anaconda3/envs/lmdrive_pyc2.0.1_py3.8/lib/python3.8/site-packages/diffusers/models/cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
deprecate(
pygame 2.6.0 (SDL 2.28.4, Python 3.8.19)
Hello from the pygame community. https://www.pygame.org/contribute.html

========= Preparing RouteScenario_3 (repetition 0) =========

Setting up the agent
build model...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00, 2.00s/it]
Loading Q-Former
load model...
Data save path: benchmark_long_09_02_09_59_48

Could not set up the required agent:

[Errno 13] Permission denied: 'data/eval/benchmark_long_09_02_09_59_48'

Traceback (most recent call last):
File "leaderboard/leaderboard/leaderboard_evaluator.py", line 272, in _load_and_run_scenario
self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
File "/home/syl/LMDrive/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in init
self.setup(path_to_conf_file)
File "/home/syl/LMDrive/leaderboard/team_code/lmdriver_agent.py", line 237, in setup
self.save_path.mkdir(parents=True, exist_ok=False)
File "/home/mepus/anaconda3/envs/lmdrive_pyc2.0.1_py3.8/lib/python3.8/pathlib.py", line 1288, in mkdir
self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'data/eval/benchmark_long_09_02_09_59_48'

Registering the route statistics
Traceback (most recent call last):
File "leaderboard/leaderboard/leaderboard_evaluator.py", line 272, in _load_and_run_scenario
self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
File "/home/syl/LMDrive/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in init
self.setup(path_to_conf_file)
File "/home/syl/LMDrive/leaderboard/team_code/lmdriver_agent.py", line 237, in setup
self.save_path.mkdir(parents=True, exist_ok=False)
File "/home/mepus/anaconda3/envs/lmdrive_pyc2.0.1_py3.8/lib/python3.8/pathlib.py", line 1288, in mkdir
self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'data/eval/benchmark_long_09_02_09_59_48'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "leaderboard/leaderboard/leaderboard_evaluator.py", line 483, in main
leaderboard_evaluator.run(arguments)
File "leaderboard/leaderboard/leaderboard_evaluator.py", line 418, in run
self._load_and_run_scenario(args, config)
File "leaderboard/leaderboard/leaderboard_evaluator.py", line 308, in _load_and_run_scenario
self._register_statistics(config, args.checkpoint, entry_status, crash_message)
File "leaderboard/leaderboard/leaderboard_evaluator.py", line 249, in _register_statistics
self.statistics_manager.save_record(current_stats_record, config.index, checkpoint)
File "/home/syl/LMDrive/leaderboard/leaderboard/utils/statistics_manager.py", line 253, in save_record
save_dict(endpoint, data)
File "/home/syl/LMDrive/leaderboard/leaderboard/utils/checkpoint_tools.py", line 76, in save_dict
with open(endpoint, 'w') as fd:
PermissionError: [Errno 13] Permission denied: 'results/sample_result.json'

**Comment by mobiiin** [comment]
could you share ur environment yaml file with me? I'm having issues with the pygame. its most probably dependency issue

**Comment by CoderXuans** [comment]
which yaml file?

**Comment by mobiiin** [comment]
the environment in which you successfully ran the LMDrive. could you create a yaml file of your environment and share it?

**Comment by CoderXuans** [comment]
You can check the answers under other questions. I remember someone provided the configuration file.
