### ISSUE TITLE
RuntimeError: Python version >= 3.9 required

### ISSUE THREAD

**Issue by 18445864529** [opendilab/LMDrive#8]
The specified python version as suggested is 3.8, but after executing the following 
```
conda create -n lmdrive python=3.8
conda activate lmdrive
cd vision_encoder
python setup.py develop
```
I got this error:
```
  File "/tmp/easy_install-7_5rk8p_/numpy-1.26.3/setup.py", line 22, in <module>
    author_email="hello@rwightman.com",
RuntimeError: Python version >= 3.9 required.
```
Could you test this and suggest a solution? Thanks.

**Comment by deepcs233** [comment]
Hi!
Can you provide the complete traceback log? It can help me fix the bug in the later version.

Based on the current log, maybe you can try to remove the version requirement for the numpy or the other package. Or remove the package in the file `vision_encoder/requirements.txt`.

**Comment by 18445864529** [comment]
Here's the full traceback @deepcs233 
```
running develop
/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing timm.egg-info/PKG-INFO
writing dependency_links to timm.egg-info/dependency_links.txt
writing requirements to timm.egg-info/requires.txt
writing top-level names to timm.egg-info/top_level.txt
reading manifest file 'timm.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'timm.egg-info/SOURCES.txt'
running build_ext
Creating /data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/timm.egg-link (link to .)
timm 0.4.13 is already the active version in easy-install.pth

Installed /data/a/bowenz/LMDrive/vision_encoder
Processing dependencies for timm==0.4.13
Searching for numpy
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/d0/b0/13e2b50c95bfc1d5ee04925eb5c105726c838f922d0aaddd57b7c8be0f8b/numpy-1.26.3.tar.gz#sha256=697df43e2b6310ecc9d95f05d5ef20eacc09c7c4ecc9da3f235d39e71b7da1e4
Best match: numpy 1.26.3
Processing numpy-1.26.3.tar.gz
Writing /tmp/easy_install-a4q4fjp2/numpy-1.26.3/setup.cfg
Running numpy-1.26.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-a4q4fjp2/numpy-1.26.3/egg-dist-tmp-mux89e1l
Traceback (most recent call last):
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-a4q4fjp2/numpy-1.26.3/setup.py", line 22, in <module>
    author_email="hello@rwightman.com",
RuntimeError: Python version >= 3.9 required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    setup(
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/develop.py", line 124, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 788, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1135, in best_match
    return self.obtain(req, installer)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1147, in obtain
    return installer(requirement)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 713, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 738, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 932, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1206, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1192, in run_setup
    run_setup(setup_script, args)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 262, in run_setup
    raise
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/data/a/bowenz/anaconda3/envs/lmdrive/lib/python3.8/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-a4q4fjp2/numpy-1.26.3/setup.py", line 22, in <module>
    author_email="hello@rwightman.com",
RuntimeError: Python version >= 3.9 required.
```

**Comment by deepcs233** [comment]
Have you installed the timm before? If so, you need to uninstall it and re-install our module.

**Comment by deepcs233** [comment]
Hi!
Can you try to install the numpy before running `python setup.py develop`?

For example:

1. pip install numpy
2. cd vision_encoder
3. python setup.py develop

**Comment by deepcs233** [comment]
Also, I have updated the `Setup` section in readme and some files in the repo. Please use the latest version.

**Comment by chan-yuu** [comment]
pip install spacy==3.5.1

**Comment by ni-eminen** [comment]
@18445864529 did you face any issues using the upgraded python >=3.9?

**Comment by nguyenhuykhang** [comment]
I use spacy which supports python 3.8
